name: Auto Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  # Use PAT instead of default
          WITH_V: true
