name: Validate HTML

on:
  push:
    branches: [main]
  pull_request:

jobs:
  html-validate:
    name: Run HTML Validator
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install html-validate
        run: npm install -g html-validate

      - name: Validate all HTML files
        run: html-validate "**/*.html"
